name: Merge to main Pipeline
on:
  push:
    branches:
      - main

jobs:
  sonar_scan:
    name: CodeScan
    uses: meetash/github-workflows/.github/workflows/sonarcloud.yaml@v8
    with:
      skip_coverage: true
    secrets:
      sonar_token: ${{ secrets.SONAR_TOKEN }}
